# Generated by Django 5.1.4 on 2024-12-23 15:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('b_buildingtype', models.CharField(choices=[('Residential', 'مسکونی'), ('Commercial', 'تجاری'), ('Office', 'اداری')], default='Residential', max_length=15)),
                ('b_year_build', models.DateField()),
                ('b_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('b_image', models.ImageField(blank=True, null=True, upload_to='building_images/')),
                ('b_name', models.CharField(max_length=50)),
                ('b_address', models.CharField(max_length=255)),
                ('b_num_floor', models.PositiveIntegerField()),
                ('b_num_of_units_in_every_floor', models.PositiveIntegerField()),
                ('b_create_data_at', models.DateTimeField(auto_now_add=True)),
                ('b_update_data_at', models.DateTimeField(auto_now=True)),
                ('b_manager_name', models.CharField(max_length=100)),
                ('b_manager_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('b_is_active', models.BooleanField(default=True)),
                ('b_post_code', models.CharField(blank=True, max_length=15, null=True)),
                ('b_security_manager_name', models.CharField(blank=True, max_length=100, null=True)),
                ('b_security_manager_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('b_cost_charge_for_every_units', models.PositiveIntegerField(default=0)),
                ('b_cost_buildings', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('agenda', models.TextField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='building.building')),
            ],
        ),
    ]
